config/routes.rb
MyCloud::Application.routes.draw do
  resources :ipaddrs

  resources :vminfos do
    collection do
     get 'poweron'
     get 'templates'
     get 'poweroff'
     get 'migrate'
     get 'clone'
     get 'reconfig'
     get 'reconfig_edit'
     post 'poweron'
     post 'templates'
     post 'poweroff'
     post 'migrate'
     post 'clone'
     post 'reconfig'
     post 'reconfig_edit'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq' 

  

end

app/models/ipaddr.rb
class Ipaddr < ActiveRecord::Base
end

app/controllers/ipaddrs_controller.rb
class IpaddrsController < ApplicationController
  before_action :set_ipaddr, only: [:show, :edit, :update, :destroy]

  # GET /ipaddrs
  # GET /ipaddrs.json
  def index
    @ipaddrs = Ipaddr.all
  end

  # GET /ipaddrs/1
  # GET /ipaddrs/1.json
  def show
  end

  # GET /ipaddrs/new
  def new
    @ipaddr = Ipaddr.new
  end

  # GET /ipaddrs/1/edit
  def edit
  end

  # POST /ipaddrs
  # POST /ipaddrs.json
  def create
    @ipaddr = Ipaddr.new(ipaddr_params)

    respond_to do |format|
      if @ipaddr.save
        format.html { redirect_to @ipaddr, notice: 'Ipaddr was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ipaddr }
      else
        format.html { render action: 'new' }
        format.json { render json: @ipaddr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ipaddrs/1
  # PATCH/PUT /ipaddrs/1.json
  def update
    respond_to do |format|
      if @ipaddr.update(ipaddr_params)
        format.html { redirect_to @ipaddr, notice: 'Ipaddr was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ipaddr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ipaddrs/1
  # DELETE /ipaddrs/1.json
  def destroy
    @ipaddr.destroy
    respond_to do |format|
      format.html { redirect_to ipaddrs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ipaddr
      @ipaddr = Ipaddr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ipaddr_params
      params.require(:ipaddr).permit(:ipaddress, :manageno, :servername, :macaddress, :use, :remarks)
    end
end

app/helpers/ipaddrs_helper.rb
module IpaddrsHelper
end

app/views/ipaddrs/_form.html.erb
<%= form_for(@ipaddr) do |f| %>
  <% if @ipaddr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ipaddr.errors.count, "error") %> prohibited this ipaddr from being saved:</h2>

      <ul>
      <% @ipaddr.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ipaddress %><br>
    <%= f.text_field :ipaddress %>
  </div>
  <div class="field">
    <%= f.label :manageno %><br>
    <%= f.text_field :manageno %>
  </div>
  <div class="field">
    <%= f.label :servername %><br>
    <%= f.text_field :servername %>
  </div>
  <div class="field">
    <%= f.label :macaddress %><br>
    <%= f.text_field :macaddress %>
  </div>
  <div class="field">
    <%= f.label :use %><br>
    <%= f.text_field :use %>
  </div>
  <div class="field">
    <%= f.label :remarks %><br>
    <%= f.text_field :remarks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ipaddrs/edit.html.erb
<h1>Editing ipaddr</h1>

<%= render 'form' %>

<%= link_to 'Show', @ipaddr %> |
<%= link_to 'Back', ipaddrs_path %>

app/views/ipaddrs/index.html.erb
<h1>Listing ipaddrs</h1>

<table class="table table-striped table-bordered" border=1>
  <thead>
    <tr>
      <th>Ipaddress</th>
      <th>資産管理番号</th>
      <th>マシン名</th>
      <th>MacAddress</th>
      <th>用途</th>
      <th>備考</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @ipaddrs.each do |ipaddr| %>
      <tr>
        <td><%= ipaddr.ipaddress %></td>
        <td><%= ipaddr.manageno %></td>
        <td><%= ipaddr.servername %></td>
        <td><%= ipaddr.macaddress %></td>
        <td><%= ipaddr.use %></td>
        <td><%= ipaddr.remarks %></td>
        <td><%= link_to 'Show', ipaddr %></td>
        <td><%= link_to 'Edit', edit_ipaddr_path(ipaddr) %></td>
        <td><%= link_to 'Destroy', ipaddr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ipaddr', new_ipaddr_path %>

app/views/ipaddrs/new.html.erb
<h1>New ipaddr</h1>

<%= render 'form' %>

<%= link_to 'Back', ipaddrs_path %>

app/views/ipaddrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ipaddress:</strong>
  <%= @ipaddr.ipaddress %>
</p>

<p>
  <strong>Manageno:</strong>
  <%= @ipaddr.manageno %>
</p>

<p>
  <strong>Servername:</strong>
  <%= @ipaddr.servername %>
</p>

<p>
  <strong>Macaddress:</strong>
  <%= @ipaddr.macaddress %>
</p>

<p>
  <strong>Use:</strong>
  <%= @ipaddr.use %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @ipaddr.remarks %>
</p>

<%= link_to 'Edit', edit_ipaddr_path(@ipaddr) %> |
<%= link_to 'Back', ipaddrs_path %>