config/routes.rb
MyCloud::Application.routes.draw do
  resources :ipaddrs

  resources :vminfos do
    collection do
     get 'poweron'
     get 'templates'
     get 'poweroff'
     get 'migrate'
     get 'clone'
     get 'reconfig'
     get 'reconfig_edit'
     post 'poweron'
     post 'templates'
     post 'poweroff'
     post 'migrate'
     post 'clone'
     post 'reconfig'
     post 'reconfig_edit'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq' 

  

end

app/models/vminfo.rb
class Vminfo < ActiveRecord::Base
end

app/controllers/vminfos_controller.rb
class VminfosController < ApplicationController
  before_action :set_vminfo #, only: [:show, :edit, :update, :destroy]

  # GET /vminfos
  # GET /vminfos.json
  def index
  end
 
  def templates
  end

  def poweron
    @vminfo.powerOn
    redirect_to :action => 'index'
  end

  def poweroff
    @vminfo.powerOff
    redirect_to :action => 'index'
  end

  def migrate
  end

  def clone
    CloneWorker.perform_async(params[:vminfo][:name], 
                              "dev" + params[:newInfo][:cloneName],
                              params[:newInfo][:ipaddr],
                              params[:newInfo][:jsnn],
                              params[:newInfo][:jsc])
    #SshWorker.perform_async(params[:newInfo][:cloneName],params[:newInfo][:ipaddr],params[:newInfo][:jsnn],params[:newInfo][:jsc])
    redirect_to :action => 'index'
  end

  def reconfig_edit
    @cpu_Select = {"1" => 1, "2" => 2, "4" => 4}
    @mem_Select = {"512" => 512,"1024" => 1024,"2048" => 2048,"4096" => 4096}
  end
  
  def reconfig
    @vminfo.powerOff if @vminfo.powerstatus != "poweredOff"
    @vminfo.reconfig_cpuname_to(params[:cpunum])
    @vminfo.reconfig_memsize_to(params[:memsize])
    redirect_to :action => 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vminfo
      myDc = Mydatacenter.new
      @vminfos = myDc.vmArray 
      @vminfo = myDc.search_vm_by_name(params[:name])
      #@vminfo = Vminfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vminfo_params
      params.require(:vminfo).permit(:name, :path, :ipaddress)
    end
end

app/helpers/vminfos_helper.rb
module VminfosHelper
   def insert_popup_script()
     javascript_tag( "$(function () { $('[rel=popover]').popover({html: true});$('#loginModal').modal(); });")
     #javascript_tag( "$(function () { $('#loginModal').modal(); });")
   end

   def vm_popup_content(vminfo)
     content = content_tag(:a,create_vm_popup_hash(vminfo),:escape => false) do 
       vminfo.name
     end
     content.gsub(/改行/," \<br\>")
   end

   def create_vm_popup_hash(vminfo)
     {
        "rel" => "popover",
        "data-title" => vminfo.name,
        "data-html" => "true",
        "data-content" => "
           Path : #{vminfo.path}#{"改行"}
           NetWork : #{vminfo.network}
        "
     }
   end

   def power_badge_state(powerState)
     color = if powerState == "poweredOn"
        "badge-success"
     elsif powerState == "poweredOff"
        "badge-important"
     else
        "badge-warning"
     end     
     "<span class=\"badge #{color}\">#{powerState}</span>".html_safe
   end
end

app/views/vminfos/_form.html.erb
<%= form_for(@vminfo) do |f| %>
  <% if @vminfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vminfo.errors.count, "error") %> prohibited this vminfo from being saved:</h2>

      <ul>
      <% @vminfo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :ipaddress %><br>
    <%= f.text_field :ipaddress %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vminfos/_templates.html.erb
<h2>Templates</h2>
<table class="table table-striped table-bordered" border=1>
  <thead>
    <tr>
      <th>VmName</th>
      <th>Path</th>
      <th>NetWork</th>
      <th colspan="1">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @vminfos.each do |vminfo| %>
    <% if vminfo.isTemplate? %>
      <tr>
        <td><%=h vminfo.name %></td>
        <td><%=h vminfo.path %></td>
        <td><%=h vminfo.network %></td>
        <% if vminfo.name =~ /devServerXX_template$/ then %>
        <td><%=h button_to "Migrate" ,{:action =>"migrate"  ,:name => vminfo.name},:class => "btn btn-info btn-small"  %></td>
        <% else %>
        <td></td>
        <% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<br>

app/views/vminfos/_vmtable.html.erb
<h2>VMs</h2>
<table class="table table-striped table-bordered" border=1>
  <thead>
    <tr>
      <th>VmName</th>
      <th>PowerState</th>
      <th>IpAddress</th>
      <th>MacAddress</th>
      <th>CpuNum</th>
      <th>MemorySize(MB)</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @vminfos.each do |vminfo| %>
    <% if !vminfo.isTemplate? %>
      <tr>
        <td><%=raw vm_popup_content(vminfo) %></td>
        <td><%=h power_badge_state vminfo.powerstatus %></td>
        <td><%=h vminfo.ipaddress %></td>
        <td><%=h vminfo.macaddress %></td>
        <td><%=h vminfo.cpunum %></td>
        <td><%=h vminfo.memsize %></td>
        <td><%=h button_to "Start" ,{:action =>"poweron"  ,:name => vminfo.name} ,:class => "btn btn-primary btn-small"%></td>
        <td><%=h button_to "Shutdown" ,{:action =>"poweroff" ,:name => vminfo.name},:class => "btn btn-primary btn-small" %></td>
        <td><%=h button_to "Reconfig" ,{:action =>"reconfig_edit" ,:name => vminfo.name},:class => "btn btn-info btn-small" %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/vminfos/edit.html.erb
<h1>Editing vminfo</h1>

<%= render 'form' %>

<%= link_to 'Show', @vminfo %> |
<%= link_to 'Back', vminfos_path %>

app/views/vminfos/index.html.erb
<%=  render(:partial => 'vmtable') %>

app/views/vminfos/migrate.html.erb
<%=  render(:partial => 'vmtable') %>
<div class="modal" id="loginModal">
  <a href="#" class="close" data-dismiss="modal">&times;</a>
   <div class="modal-header">
      <h2>Migrate VM from template</h2>
   </div>
   <div class="modal-body">
    <%= form_tag('clone' ) do  %>
    
      <div class="field">
        <%= label_tag 'Template_vm_name:' %><br>
        <%= text_field :vminfo , :name ,:readonly => true %>
      </div>
      <div class="field">
        <%= label_tag 'New Server Name:' %><br>
        dev<%= text_field :newInfo, :cloneName %> 
      </div>
      <div class="field">
        <%= label_tag 'New Ip Addr:' %><br>
        <%= text_field :newInfo, :ipaddr %> *1
      </div>
      <div class="field">
        <%= label_tag 'Jenkins Slave Node Name:' %><br>
        <%= text_field :newInfo, :jsnn %> *2
      </div>
      <div class="field">
        <%= label_tag 'Jenkins Slave Cecret:' %><br>
        <%= text_field :newInfo, :jsc %> *2
      </div>
   </div> 
   <div class="alert alert-info">
*1 管理者に払い出しもらって下さい<br>
*2 Jenkins Slave Nodeを作成しない場合は不要<br>　　不明な場合は管理者に問い合わせて下さい
   </div> 
   <div class="modal-footer">
      <%= button_tag('Cancel' ,{:class => "btn", :type => :reset ,"data-dismiss" => "modal"} )%>
      <%= submit_tag('Clone',:class => "btn btn-info") %>
    <% end %>

   </div>
</div>

app/views/vminfos/new.html.erb
<h1>New vminfo</h1>

<%= render 'form' %>

<%= link_to 'Back', vminfos_path %>

app/views/vminfos/reconfig_edit.html.erb
 <%=  render(:partial => 'vmtable') %>
<div class="modal" id="loginModal">
  <a href="#" class="close" data-dismiss="modal">&times;</a>
   <div class="modal-header">
      <h2>Reconfig VM</h2>
   </div>
   <div class="modal-body">
   <div class="alert alert-info">
   サーバーが起動中の時合、再止されます。
   </div>
      <%= form_tag('reconfig' ) do  %>
      
        <div class="field">
          <%= hidden_field_tag(:vmname, @vminfo.name)  %>
        </div>
        <div class="field">
          <%= label_tag 'VMname:' %> <h5><%= @vminfo.name  %></h5>
        </div>
        <div class="field">
          <%= label_tag 'CPUs:' %>
          <%= select_tag :cpunum , options_for_select( @cpu_Select,@vminfo.cpunum || 1)  %>
        </div>
        <div class="field">
          <%= label_tag 'MemorySize(MB):' %>
          <%= select_tag :memsize , options_for_select( @mem_Select,@vminfo.memsize || 1024)  %>
        </div>
   </div>
   <div class="modal-footer">
        <%= button_tag('Cancel' ,{:class => "btn", :type => :reset ,"data-dismiss" => "modal"} )%>
        <%= submit_tag('Reconfig',:class => "btn btn-info") %>
      <% end %>
   </div>
</div>

app/views/vminfos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vminfo.name %>
</p>

<p>
  <strong>Path:</strong>
  <%= @vminfo.path %>
</p>

<p>
  <strong>Ipaddress:</strong>
  <%= @vminfo.ipaddress %>
</p>

<%= link_to 'Edit', edit_vminfo_path(@vminfo) %> |
<%= link_to 'Back', vminfos_path %>

app/views/vminfos/templates.html.erb
<%=  render(:partial => 'templates') %>